from flask import Flask, render_template, request, send_file
from database import db, Violation
from ml.processor import process_video

import os
import uuid
import io
import zipfile
from datetime import datetime

app = Flask(__name__)

# ================= DATABASE CONFIG =================
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///traffic_violations.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db.init_app(app)

# ================= UPLOAD CONFIG =================
UPLOAD_FOLDER = "static/uploads"
app.config["UPLOAD_FOLDER"] = UPLOAD_FOLDER


# ================= HOME =================
@app.route("/")
def home():
    return render_template("index.html")


# ================= PENALTY PAGE =================
@app.route("/penalty")
def penalty():
    return render_template("penalty.html")

@app.route("/violations")
def violations():

    all_violations = Violation.query.order_by(Violation.id.desc()).all()

    return render_template(
        "violations.html",
        violations=all_violations
    )


# ================= VIDEO UPLOAD =================
@app.route("/upload", methods=["GET", "POST"])
def upload():

    if request.method == "POST":

        video = request.files.get("video")

        if not video or video.filename == "":
            return "No video selected", 400

        os.makedirs(app.config["UPLOAD_FOLDER"], exist_ok=True)

        filename = f"{uuid.uuid4()}_{video.filename}"
        video_path = os.path.join(app.config["UPLOAD_FOLDER"], filename)

        video.save(video_path)

        # ================= AI PROCESSING =================
        result = process_video(video_path)

        # ================= SAVE VIOLATIONS TO DATABASE =================
        for i, face in enumerate(result["faces"]):

            plate_image = None

            if "plates" in result and i < len(result["plates"]):
                plate_image = result["plates"][i]

            violation = Violation(
                video_name=filename,
                violation_type="no_helmet",
                evidence_image=face,
                plate_image=plate_image,
                date_time=datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            )

            db.session.add(violation)

        db.session.commit()

        return render_template(
            "results.html",
            video_url=result["processed_video"],
            stats=result["stats"],
            faces=result["faces"],
            plates=result["plates"],
            processing_time=result["processing_time"]
        )

    return render_template("upload.html")


# ================= DOWNLOAD EVIDENCE ZIP =================
@app.route("/download_evidence")
def download_evidence():

    memory_file = io.BytesIO()

    with zipfile.ZipFile(memory_file, "w", zipfile.ZIP_DEFLATED) as zf:

        summary_text = (
            "Smart Traffic Violation Detection System\n"
            "---------------------------------------\n"
            "This ZIP contains evidence generated by the AI system.\n\n"
        )

        zf.writestr("summary.txt", summary_text)

        faces_dir = "static/outputs/faces"
        if os.path.exists(faces_dir):
            for f in os.listdir(faces_dir):
                zf.write(os.path.join(faces_dir, f), f"faces/{f}")

        plates_dir = "static/outputs/plates"
        if os.path.exists(plates_dir):
            for p in os.listdir(plates_dir):
                zf.write(os.path.join(plates_dir, p), f"plates/{p}")

    memory_file.seek(0)

    return send_file(
        memory_file,
        download_name="violation_evidence.zip",
        as_attachment=True
    )


# ================= START SERVER + CREATE DATABASE =================
if __name__ == "__main__":

    with app.app_context():
        db.create_all()
        print("Database initialized!")

    app.run(debug=True)