from flask import Flask, render_template, request, send_file
import os
import uuid
import io
import zipfile
from ml.processor import process_video

app = Flask(__name__)

UPLOAD_FOLDER = "static/uploads"
app.config["UPLOAD_FOLDER"] = UPLOAD_FOLDER


@app.route("/")
def home():
    return render_template("index.html")
@app.route("/penalty")
def penalty():
    return render_template("penalty.html")



@app.route("/upload", methods=["GET", "POST"])
def upload():
    if request.method == "POST":
        video = request.files.get("video")

        if not video or video.filename == "":
            return "No video selected", 400

        os.makedirs(app.config["UPLOAD_FOLDER"], exist_ok=True)

        filename = f"{uuid.uuid4()}_{video.filename}"
        video_path = os.path.join(app.config["UPLOAD_FOLDER"], filename)
        video.save(video_path)

        # Call MOCK / REAL ML
        result = process_video(video_path)

        return render_template(
            "results.html",
            video_url=result["processed_video"],
            stats=result["stats"],
            faces=result["faces"],
            plates=result["plates"],
            processing_time=result["processing_time"]
        )

    return render_template("upload.html")


# ================= DOWNLOAD EVIDENCE ZIP =================
@app.route("/download_evidence")
def download_evidence():
    memory_file = io.BytesIO()

    with zipfile.ZipFile(memory_file, "w", zipfile.ZIP_DEFLATED) as zf:

        # Summary file
        summary_text = (
            "Smart Traffic Violation Detection System\n"
            "---------------------------------------\n"
            "This ZIP contains evidence generated by the AI system.\n\n"
        )
        zf.writestr("summary.txt", summary_text)

        # Faces
        faces_dir = "static/outputs/faces"
        if os.path.exists(faces_dir):
            for f in os.listdir(faces_dir):
                zf.write(os.path.join(faces_dir, f), f"faces/{f}")

        # Plates
        plates_dir = "static/outputs/plates"
        if os.path.exists(plates_dir):
            for p in os.listdir(plates_dir):
                zf.write(os.path.join(plates_dir, p), f"plates/{p}")

    memory_file.seek(0)

    return send_file(
        memory_file,
        download_name="violation_evidence.zip",
        as_attachment=True
    )


if __name__ == "__main__":
    app.run(debug=True)
